# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sean Nam
email: sangwoo@seannam.com
description: >- # this means to ignore newlines until "baseurl:"
  UC San Diego B.S. Computer Science
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seannam.github.io" # the base hostname & protocol for your site

paginate:	5 # The number of posts to show per page on your homepage
paginate_path: "/blog/page:num"

name: 'Sean Nam'
bio: >
  UC San Diego Computer Science. Class of 2019.
author_image: "/assets/images/author.jpg"
twitter_username: nam_sean
github_username:  seannam
fathom_site_ID: LUXGEPES

include: ["_pages"]

# Build settings
permalink: /:title/

mailchimp: 
  user-id: 37cae49f6d9c8c7b096f2713a,
  list-id: 70d511f542

# Travis CI settings
username: seannam
repo: seannam.github.io
branch: master
destination: _site/
safe: false

markdown: kramdown

kramdown:
  parse_block_html: true

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration

plugins:
  - jekyll-paginate
  - jekyll-gist
