#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer ./_site --url-ignore "/bit.ly/snam-li/", "https://jasondoesstuff.com/unfollowing-twitter-experiment/"
